//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ES.DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EsMembers
    {
        public EsMembers()
        {
            this.MembersBrands = new HashSet<MembersBrands>();
            this.MemberUsersRoles = new HashSet<MemberUsersRoles>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string ContractNumber { get; set; }
    
        public virtual ICollection<MembersBrands> MembersBrands { get; set; }
        public virtual ICollection<MemberUsersRoles> MemberUsersRoles { get; set; }
    }
}
