//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ES.DataAccess.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EsStockDbEntities : DbContext
    {
        public EsStockDbEntities()
            : base("name=EsStockDbEntities")
        {
        }
        public EsStockDbEntities(string connectionString)
            : base(connectionString)
        {
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EsMembers> EsMembers { get; set; }
        public virtual DbSet<ESSharedProducts> ESSharedProducts { get; set; }
    }
}
